# -*- coding: utf-8 -*-
"""Licence_Plate_Detection_YOLO_V8.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/14aZfI-P2ASsuMGNBargnLW2gqb9oh3uk
"""

!git clone https://github.com/Arijit1080/Licence-Plate-Detection-using-YOLO-V8.git

cd /content/Licence-Plate-Detection-using-YOLO-V8

!pip install roboflow

from roboflow import Roboflow
rf = Roboflow(api_key="20SCzvqDs2XgUk8E8pX6")
project = rf.workspace("mochoye").project("license-plate-detector-ogxxg")
version = project.version(2)
dataset = version.download("yolov8")

!pip install -r requirements.txt

!python /content/Licence-Plate-Detection-using-YOLO-V8/ultralytics/yolo/v8/detect/train.py model=yolov8n.pt data=/content/Licence-Plate-Detection-using-YOLO-V8/License-Plate-Detector-2/data.yaml epochs=100

!python /content/Licence-Plate-Detection-using-YOLO-V8/ultralytics/yolo/v8/detect/predict.py model='/content/Licence-Plate-Detection-using-YOLO-V8/best.pt' source='/content/Licence-Plate-Detection-using-YOLO-V8/demo.mp4'

!python /content/Licence-Plate-Detection-using-YOLO-V8/ultralytics/yolo/v8/detect/predict.py model='/content/Licence-Plate-Detection-using-YOLO-V8/runs/detect/train11/weights/best.pt' source='/content/Licence-Plate-Detection-using-YOLO-V8/nm.jpeg'